apiVersion: apps/v1
kind: Deployment
metadata:
  name: sito-deployment
spec:
  replicas: 2 # Diciamo a K8s di far girare 2 copie del sito!
  selector:
    matchLabels:
      app: mio-sito
  template:
    metadata:
      labels:
        app: mio-sito
    spec:
      containers:
        - name: sito-container
          image: mio-sito-k8s:v1
          imagePullPolicy: IfNotPresent # Usa l'immagine locale che abbiamo caricato
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sito-service
spec:
  type: LoadBalancer # Crea un bilanciatore di carico
  selector:
    app: mio-sito
  ports:
    - port: 80
      targetPort: 80